# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Cytrus

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Manifest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Manifest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsManifest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Manifest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Manifest
    def Fragments(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cytrus.Fragment import Fragment
            obj = Fragment()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Manifest
    def FragmentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Manifest
    def FragmentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ManifestStart(builder): builder.StartObject(1)
def Start(builder):
    return ManifestStart(builder)
def ManifestAddFragments(builder, fragments): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(fragments), 0)
def AddFragments(builder, fragments):
    return ManifestAddFragments(builder, fragments)
def ManifestStartFragmentsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartFragmentsVector(builder, numElems):
    return ManifestStartFragmentsVector(builder, numElems)
def ManifestEnd(builder): return builder.EndObject()
def End(builder):
    return ManifestEnd(builder)