name: Flow A

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/DofusInvoker.swf'

jobs:
  Flow_A:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: A1 - Extract DofusInvoker.swf
        run: |
          chmod +x src/A1.sh
          src/A1.sh data/DofusInvoker.swf data/DofusInvoker/

      - name: A2 - Build .json
        run: |
            python src/A2.py data/DofusInvoker/scripts/com/ data/events.json
      
      - name: Get latest Dofus version
        run: |
          chmod +x devscript/latest-dofus-version.sh
          export DOFUS_VERSION=$(./devscript/latest-dofus-version.sh)
          echo The current Dofus version is $DOFUS_VERSION
          echo "::set-env name=VERSION::$DOFUS_VERSION"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - uses: EndBug/add-and-commit@v7
        with:
          add: '["data/DofusInvoker/", "data/events.json"]'
          message: 'Flow A - Update version ${{ env.VERSION }}'
          push: true
