name: Flow C
 
on:
  workflow_dispatch:
  push:
    paths:
      - 'data/d2i/*'
    branches:
      - master

jobs:
  Flow_C:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: C1 - Build .json
        run: |
            python src/C1.py data/d2i/ data/translations_json/
          
      - name: Get latest Dofus version
        run: |
          chmod +x devscript/latest-dofus-version.sh
          export DOFUS_VERSION=$(devscript/latest-dofus-version.sh)
          echo The current Dofus version is $DOFUS_VERSION
          echo "::set-env name=VERSION::$DOFUS_VERSION"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: '["data/entities_json/"]'
          message: 'Flow C - Update version ${{ env.VERSION }}'
          push: true
