name: Publish

on:
  workflow_run:
    workflows: ["Flow A", "Flow B", "Flow C"]
    branches: [master]
    types:
      - completed

jobs:

  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Publish
        run: |
          echo "This is Publish"
