name: Events

on:
  workflow_dispatch:
  push:
    paths:
      - 'database/DofusInvoker/scripts/com/**'
    branches:
      - master

jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Wait for flows to end and success
        uses: 

      - name: Get latest Dofus version
        run: |
          chmod +x devscript/latest-dofus-version.sh
          export DOFUS_VERSION=$(./devscript/latest-dofus-version.sh)
          echo The current Dofus version is $DOFUS_VERSION
          echo "::set-env name=VERSION::$DOFUS_VERSION"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - uses: EndBug/add-and-commit@v7
        with:
          add: '["database/events.json"]'
          message: 'Update version ${{ env.VERSION }}'
          push: true

      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ env.VERSION }}
          prerelease: false
          title: ${{ env.VERSION }}
          files: |
            ./database/events.json
          
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.VERSION }}
