name: Update

on:
  workflow_dispatch:

jobs:
  Job_U:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: U1 - Update Dofus Client
        run: |
          .\src\U1\U1.ps1 src\U1\project.json data\U1\swf\ data\U1\d2o\ data\U1\d2i\

      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: Job_U
          path: |
            data/U1/

  Job_A:
    runs-on: ubuntu-latest
    needs: [Job_U]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: Job_U
          path: data/U1/swf/
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: data/U1/

  Job_B:
    runs-on: ubuntu-latest
    needs: [Job_U]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: Job_U
          path: data/U1/d2o/
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: data/U1/

  Job_C:
    runs-on: ubuntu-latest
    needs: [Job_U]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: Job_U
          path: data/U1/d2i/
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: data/U1/
